disp("4.8.5 Smallest number for sum of x and y")
disp("Consider two numbers, x, y")
disp("We need to find the smallest value")
disp("for the equation x^3 + y^2 = S")
disp("when x + y = 10")
disp("Lets substitute y in the function")
disp("for y = 10 - x")
disp("Then we get: ")
disp("S = x^3 + (10 - x)^2")
disp("To find when the function is smallest")
disp("We derive it to find a minimum")
disp("S' = 3x^2 + 2*(10 - x)*-1")
disp("S' = 3x^2 + 2x - 20")
disp("Now to find x when S' = 0")
disp("x = ")
Sprime = @(x) 3*x^2 + 2*x - 20;
disp(fzero(Sprime, 0))
disp("Thus y = ")
disp("")
disp(10 - fzero(Sprime, 0))
disp("And our minimum for S is:")
x = fzero(Sprime, 0);
y = 10 - fzero(Sprime, 0);
disp(x^3 + (y)^2)